In [1]:
# Testing methods and functions in POVM.py
import numpy as np

In [31]:
cd ..

/home/abhishekabhishek/git/AQT-KimGroup


In [32]:
import povm as P

Exploring Pauli-6 and Pauli-4 POVMs

In [13]:
Na = 6

In [14]:
v0 = np.array([[1], [0]])
print(v0, v0.shape)

[[1]
 [0]] (2, 1)


In [15]:
m00 = np.matmul(v0, np.conj(np.transpose(v0)))
print(m00)

[[1 0]
 [0 0]]


In [16]:
V0 = np.array([[1], [0]])
V1 = np.array([[0], [1]])
Vp = (1./np.sqrt(2))*np.array([[1], [1]])
Vm = (1./np.sqrt(2))*np.array([[1], [-1]])
Vr = (1./np.sqrt(2))*np.array([[1], [1j]])
Vl = (1./np.sqrt(2))*np.array([[1], [-1j]])

M00 = np.matmul(V0, np.conj(np.transpose(V0)))
M11 = np.matmul(V1, np.conj(np.transpose(V1)))
Mpp = np.matmul(Vp, np.conj(np.transpose(Vp)))
Mmm = np.matmul(Vm, np.conj(np.transpose(Vm)))
Mrr = np.matmul(Vr, np.conj(np.transpose(Vr)))
Mll = np.matmul(Vl, np.conj(np.transpose(Vl)))

In [17]:
print(M00, M11, Mpp, Mmm, Mrr, Mll, sep='\n')

[[1 0]
 [0 0]]
[[0 0]
 [0 1]]
[[0.5 0.5]
 [0.5 0.5]]
[[ 0.5 -0.5]
 [-0.5  0.5]]
[[0.5+0.j  0. -0.5j]
 [0. +0.5j 0.5+0.j ]]
[[0.5+0.j  0. +0.5j]
 [0. -0.5j 0.5+0.j ]]


In [19]:
M = np.zeros((Na, len(V0), len(V0)), dtype=complex)
M[0] = (1./3)*M00
M[1] = (1./3)*Mpp
M[2] = (1./3)*Mrr
M[3] = (1./3)*M11
M[4] = (1./3)*Mmm
M[5] = (1./3)*Mll
print(M)

[[[ 0.33333333+0.j          0.        +0.j        ]
  [ 0.        +0.j          0.        +0.j        ]]

 [[ 0.16666667+0.j          0.16666667+0.j        ]
  [ 0.16666667+0.j          0.16666667+0.j        ]]

 [[ 0.16666667+0.j          0.        -0.16666667j]
  [ 0.        +0.16666667j  0.16666667+0.j        ]]

 [[ 0.        +0.j          0.        +0.j        ]
  [ 0.        +0.j          0.33333333+0.j        ]]

 [[ 0.16666667+0.j         -0.16666667+0.j        ]
  [-0.16666667+0.j          0.16666667+0.j        ]]

 [[ 0.16666667+0.j          0.        +0.16666667j]
  [ 0.        -0.16666667j  0.16666667+0.j        ]]]


In [33]:
for xyz in range(8):
    print(P.int2basestr(xyz, 2, l=3))

[0, 0, 0]
[0, 0, 1]
[0, 1, 0]
[0, 1, 1]
[1, 0, 0]
[1, 0, 1]
[1, 1, 0]
[1, 1, 1]


In [35]:
P.basestr2int([0, 1, 1], 2)

3

Pauli-4 POVM

In [37]:
Vz = np.array([[[1],[0]], [[0],[1]]])
Vx = (1./np.sqrt(2))*np.array([[[1],[1]], [[1],[-1]]])
Vy = (1./np.sqrt(2))*np.array([[[1],[1j]], [[1],[-1j]]])

print(Vz, Vx, Vy, Vz.shape, sep='\n')

[[[1]
  [0]]

 [[0]
  [1]]]
[[[ 0.70710678]
  [ 0.70710678]]

 [[ 0.70710678]
  [-0.70710678]]]
[[[0.70710678+0.j        ]
  [0.        +0.70710678j]]

 [[0.70710678+0.j        ]
  [0.        -0.70710678j]]]
(2, 2, 1)


In [38]:
Mz = np.array([np.matmul(V, np.conj(np.transpose(V))) for V in Vz])
Mx = np.array([np.matmul(V, np.conj(np.transpose(V))) for V in Vx])
My = np.array([np.matmul(V, np.conj(np.transpose(V))) for V in Vy])

print(Mz, Mx, My, Mz.shape, sep='\n')

[[[1 0]
  [0 0]]

 [[0 0]
  [0 1]]]
[[[ 0.5  0.5]
  [ 0.5  0.5]]

 [[ 0.5 -0.5]
  [-0.5  0.5]]]
[[[0.5+0.j  0. -0.5j]
  [0. +0.5j 0.5+0.j ]]

 [[0.5+0.j  0. +0.5j]
  [0. -0.5j 0.5+0.j ]]]
(2, 2, 2)


In [39]:
import time

In [40]:
t = time.time()

In [44]:
print(f'Took {round(((time.time()-t)/60), 2)} minutes')

Took 0.62 minutes


In [46]:
Na, Nq = 6, 2
print([P.int2basestr(n, Na, l=Nq) for n in range(Na**Nq)])

[[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [1, 0], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [2, 0], [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [3, 0], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [5, 0], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5]]


In [47]:
import torch

In [49]:
trg = torch.Tensor([1, 3, 3, 3, 2])
pad = 0

In [61]:
tgt_mask = (trg != pad)
tgt_mask, tgt_mask.size()

(tensor([True, True, True, True, True]), torch.Size([5]))

In [62]:
tgt_mask = tgt_mask.unsqueeze(-2)
tgt_mask, tgt_mask.size()

(tensor([[True, True, True, True, True]]), torch.Size([1, 5]))

In [1]:
import torch

In [8]:
a = torch.randn(2, 4)

In [9]:
a

tensor([[-0.8247, -1.1433, -2.3368,  0.1667],
        [ 0.0287,  0.0677, -0.1217, -0.7830]])

In [25]:
tgt = a[:, :-1]
tgt, tgt.size()

(tensor([[-0.8247, -1.1433, -2.3368],
         [ 0.0287,  0.0677, -0.1217]]),
 torch.Size([2, 3]))

In [26]:
pad = 0

In [27]:
tgt_mask = (tgt != pad).unsqueeze(-2)

In [28]:
tgt_mask.size()

torch.Size([2, 1, 3])

In [ ]:
n_qubits = 3
size = n_qubits+1
attn_shape = (1, size, size)
subsequent_mask = np.triu(np.ones(attn_shape), k=1).astype('uint8')